name: Get Unity License

on: push

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v4
      - uses: actions/upload-artifact@v4
        with:
          name: UnityLicenseFile
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
