name: Unity License

on: workflow_dispatch

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v4
      - uses: actions/upload-artifact@v4
        with:
          name: UnityLicenseFile
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
